### ISSUE TITLE
Train & Test data selection + Benchmarking of a model

### ISSUE THREAD

**Issue by riseldakodra** [marcpaga/nanopore_benchmark#10]
Hello, 
I am trying to benchmark the properly_trained model you have offered here, and also the bonito_2000 model, I found on one of your issues, but I have a few questions. To benchmark it, I am using the wick test dataset, that I obtained from the links you have provided in this repo.
First of all, I want to ask how do you select which reads to use for training and testing? I checked the first supplement given in your paper, but I didn't fully understand how each number of reads was selected for each species. Did you select the best reads? If yes, how did you do that?
Secondly, did you use some of the species for both training and testing? If yes, does it mean that the folders I get from downloading the data are not 100% accurate? In the wick dataset, there are two folders, one called train and one called test. Do these names hold, or have you mixed all the data? If yes, how?
Finally, I don't understand how you get plots for one model across all the species. I am able to generate csv files for each species in the wick test dataset, using the same model to generate the fastqs for each of them, but I cannot combine those results in a single report or plot. How can I do that?
Thank you very much in advance,
Best regards.

**Comment by marcpaga** [comment]
1. Reads were selected at random. You can find which reads were used for training and testing here: https://github.com/marcpaga/nanopore_benchmark/tree/main/static/tasks

2. That depends on which task you refer to. For the global task, all species are used at train and test. For the interspecies task some species are only used at test. Again, these files contain which reads are used for training and testing for each task: https://github.com/marcpaga/nanopore_benchmark/tree/main/static/tasks

3. You may need some coding skills to get the exact plot that you desire. This would fall outside the scope of an issue here. Best is to ask at for help at [stackoverflow](https://stackoverflow.com/), or perhaps a GPT model can help you with that.

**Comment by riseldakodra** [comment]
Thank you for 1. & 2. 
Maybe I didn't explain myself clearly for 3. 
In this repo there are 2 scripts for generating reports and plots. Did you use these for obtaining the graphs in the paper/supplement? 
If yes, I see that there you include results only per model and not per species. How did you combine the results from each species using these scripts? Or is there another step that is not included in this repo?

**Comment by marcpaga** [comment]
I understand better now. The graphs in the paper were done using custom scripts. The scripts provided here are just meant to be used for quick simple plots.

**Comment by riseldakodra** [comment]
Okay, thank you for letting me know.
