### ISSUE TITLE
A problem in evaluate.py 

### ISSUE THREAD

**Issue by zwshan** [marcpaga/nanopore_benchmark#2]
when I run the code:
`python /workspace/nanopore_benchmark/evaluate.py \
--basecalls-path /workspace/startBench/catcaller \
--references-path /workspace/Staphylococcus_aureus_CAS38_02_reference.fasta \
--model-name catcaller`
it occurs
<img width="641" alt="image" src="https://user-images.githubusercontent.com/62176674/230773704-07da0a38-e1d5-43b7-97d6-160671edd260.png">
what should I do?

**Comment by marcpaga** [comment]
The script expects that the reference fasta file contains the reference sequence for each read. Is this what you have, or are you using a reference genome as reference?

**Comment by zwshan** [comment]
Yes, I am using a reference genome as reference. I run the download script provided in [nanopore_benchmark](https://github.com/marcpaga/nanopore_benchmark). I am testing the wick's test gnome, but I don't know how to translate reference genome to  reference fasta file contains the reference sequence for each read.
Maybe I should use minimap2?

**Comment by marcpaga** [comment]
minimap2 should work. You can map each read, then get the chromosome, start and end positions of each mapping and write the reference sequence that corresponds to that regions to a fasta file with `>read_id`.

**Comment by zwshan** [comment]
thank you! I will try it!

**Comment by Chenyh368** [comment]
I have the same problem when reproducing the results of Human Datasets. After training and basecalling,  how can I get the right reference .fasta file from the .fna file? Is there any script? In addition, when I use mappy to find the reference of the basecalling result in Homo_sapiens.fna using the same test set, I get multiple results or null. Is there any standard reference you can provide(e.g. corresponding reference fasta file for reads in [human_task_test_reads.txt])? Thank you!

**Comment by marcpaga** [comment]
I have added support to evaluate against a reference genome, essentially use `evaluate_referencegenome.py` instead of `evaluate.py`.

For the human task you can use the T2T reference genome (CHM13v2) as the data comes from the T2T consortium.
